# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Link(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, href: str=None, text: str=None):  # noqa: E501
        """Link - a model defined in Swagger

        :param href: The href of this Link.  # noqa: E501
        :type href: str
        :param text: The text of this Link.  # noqa: E501
        :type text: str
        """
        self.swagger_types = {
            'href': str,
            'text': str
        }

        self.attribute_map = {
            'href': 'href',
            'text': 'text'
        }
        self._href = href
        self._text = text

    @classmethod
    def from_dict(cls, dikt) -> 'Link':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Link of this Link.  # noqa: E501
        :rtype: Link
        """
        return util.deserialize_model(dikt, cls)

    @property
    def href(self) -> str:
        """Gets the href of this Link.


        :return: The href of this Link.
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href: str):
        """Sets the href of this Link.


        :param href: The href of this Link.
        :type href: str
        """

        self._href = href

    @property
    def text(self) -> str:
        """Gets the text of this Link.


        :return: The text of this Link.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text: str):
        """Sets the text of this Link.


        :param text: The text of this Link.
        :type text: str
        """

        self._text = text
