# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.team_channels import TeamChannels  # noqa: F401,E501
from swagger_server import util


class Team(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, channels: List[TeamChannels]=None):  # noqa: E501
        """Team - a model defined in Swagger

        :param name: The name of this Team.  # noqa: E501
        :type name: str
        :param channels: The channels of this Team.  # noqa: E501
        :type channels: List[TeamChannels]
        """
        self.swagger_types = {
            'name': str,
            'channels': List[TeamChannels]
        }

        self.attribute_map = {
            'name': 'name',
            'channels': 'channels'
        }
        self._name = name
        self._channels = channels

    @classmethod
    def from_dict(cls, dikt) -> 'Team':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Team of this Team.  # noqa: E501
        :rtype: Team
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Team.


        :return: The name of this Team.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Team.


        :param name: The name of this Team.
        :type name: str
        """

        self._name = name

    @property
    def channels(self) -> List[TeamChannels]:
        """Gets the channels of this Team.


        :return: The channels of this Team.
        :rtype: List[TeamChannels]
        """
        return self._channels

    @channels.setter
    def channels(self, channels: List[TeamChannels]):
        """Sets the channels of this Team.


        :param channels: The channels of this Team.
        :type channels: List[TeamChannels]
        """

        self._channels = channels
