# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TeamChannels(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, type: str=None, addresses: List[str]=None):  # noqa: E501
        """TeamChannels - a model defined in Swagger

        :param type: The type of this TeamChannels.  # noqa: E501
        :type type: str
        :param addresses: The addresses of this TeamChannels.  # noqa: E501
        :type addresses: List[str]
        """
        self.swagger_types = {
            'type': str,
            'addresses': List[str]
        }

        self.attribute_map = {
            'type': 'type',
            'addresses': 'addresses'
        }
        self._type = type
        self._addresses = addresses

    @classmethod
    def from_dict(cls, dikt) -> 'TeamChannels':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Team_channels of this TeamChannels.  # noqa: E501
        :rtype: TeamChannels
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this TeamChannels.


        :return: The type of this TeamChannels.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this TeamChannels.


        :param type: The type of this TeamChannels.
        :type type: str
        """

        self._type = type

    @property
    def addresses(self) -> List[str]:
        """Gets the addresses of this TeamChannels.


        :return: The addresses of this TeamChannels.
        :rtype: List[str]
        """
        return self._addresses

    @addresses.setter
    def addresses(self, addresses: List[str]):
        """Sets the addresses of this TeamChannels.


        :param addresses: The addresses of this TeamChannels.
        :type addresses: List[str]
        """

        self._addresses = addresses
